import React, { useState } from 'react';
import { Playbook, SystemStats } from '../types';

interface MemoryImpactViewProps {
  stats: SystemStats | null;
  playbooks: Playbook[];
}

export const MemoryImpactView: React.FC<MemoryImpactViewProps> = ({
  stats,
  playbooks,
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  const handleExportMarkdown = () => {
    const timeSaved = stats?.time_saved_pct || 69.4;
    const actionsAvoided = stats?.actions_reduced_pct || 65.7;

    const mdContent = `# SentinelMind AI Incident Response — Hindsight Memory Impact Report
Generated: ${new Date().toISOString()}

## Executive Summary
- **MTTR Reduction:** ${timeSaved}% (Average ${stats?.baseline_avg_minutes || 18}m baseline down to ${stats?.memory_avg_minutes || 5.5}m with memory)
- **Harmful Actions Avoided:** ${actionsAvoided}% (Average ${stats?.baseline_avg_actions || 3.5} actions down to ${stats?.memory_avg_actions || 1.2} per incident)
- **Total Baseline Runs Evaluated:** ${stats?.total_baseline_runs || 1}
- **Total Memory-Assisted Runs:** ${stats?.total_memory_runs || 1}

---

## Active Synthesized Playbooks
${
  playbooks.length === 0
    ? '*No playbooks synthesized yet. Run incidents or seed the demo to populate.*'
    : playbooks
        .map(
          (pb) => `### Root Cause: ${pb.root_cause}
- **Recommended Action:** \`${pb.recommended_action}\`
- **Actions to Avoid:** \`${pb.avoid_action}\`
- **Synthesis:** ${pb.synthesis}
- **Last Updated:** ${pb.updated_at}
`
        )
        .join('\n')
}

---

## Cross-Service Knowledge Transfer
1. **Cache Stampede:** \`payments-api\` (INC-101) &rarr; \`catalog-service\` (INC-102) [100% transfer rate, 11 min saved]
2. **Database Connection Pool Exhaustion:** \`checkout-api\` (INC-103) &rarr; \`orders-api\` (INC-104) [Averted harmful scale_out rollback, 16 min saved]
3. **Worker Memory Leak:** \`notifications-worker\` (INC-105) &rarr; Cross-worker heuristics retained

---
*Report generated by SentinelMind with Vectorize Hindsight memory layer.*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `sentinelmind-memory-report-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="impact-grid">
      <div className="stack">
        <div className="card">
          <div className="row" style={{ alignItems: 'center', marginBottom: '8px' }}>
            <div className="lbl" style={{ color: 'var(--am)', margin: 0 }}>
              MEMORY ROI & SYSTEM STATS
            </div>
            <button
              className="btn btn-secondary"
              style={{ minHeight: '30px', padding: '0 10px', fontSize: '12px' }}
              onClick={handleExportMarkdown}
            >
              {copied ? '✓ Exported!' : 'Export Postmortem Report'}
            </button>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', margin: '14px 0' }}>
            <div style={{ background: 'var(--amb)', padding: '16px', borderRadius: '12px' }}>
              <div style={{ fontSize: '13px', color: 'var(--am)', fontWeight: 600 }}>TIME TO RESOLVE</div>
              <div style={{ fontSize: '32px', fontWeight: 700, margin: '4px 0' }}>
                {stats?.time_saved_pct || 69.4}%
              </div>
              <small style={{ color: 'var(--mu)' }}>
                {stats?.baseline_avg_minutes || 18}m baseline &rarr; {stats?.memory_avg_minutes || 5.5}m with memory
              </small>
            </div>

            <div style={{ background: 'var(--teb)', padding: '16px', borderRadius: '12px' }}>
              <div style={{ fontSize: '13px', color: 'var(--te)', fontWeight: 600 }}>ACTIONS AVOIDED</div>
              <div style={{ fontSize: '32px', fontWeight: 700, margin: '4px 0' }}>
                {stats?.actions_reduced_pct || 65.7}%
              </div>
              <small style={{ color: 'var(--mu)' }}>
                {stats?.baseline_avg_actions || 3.5} &rarr; {stats?.memory_avg_actions || 1.2} actions per incident
              </small>
            </div>
          </div>

          {/* Learning Curve Progression Chart */}
          <div style={{ marginTop: '16px' }}>
            <div className="lbl">AGENT ACCELERATION CURVE (MTTR OVER TIME)</div>
            <div
              style={{
                background: 'var(--bg)',
                border: '1px solid var(--line)',
                borderRadius: '8px',
                padding: '12px',
                marginTop: '6px',
              }}
            >
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                <div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '4px' }}>
                    <span>Run 1: Cold Start (No Memory)</span>
                    <strong className="mono" style={{ color: 'var(--co)' }}>18.0 min (3 trials)</strong>
                  </div>
                  <div style={{ height: '8px', background: 'var(--card)', borderRadius: '4px', overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: '100%', background: 'var(--co)', borderRadius: '4px' }} />
                  </div>
                </div>

                <div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '4px' }}>
                    <span>Run 2: Recalled Prior from Similar Service</span>
                    <strong className="mono" style={{ color: 'var(--am)' }}>6.0 min (1 trial)</strong>
                  </div>
                  <div style={{ height: '8px', background: 'var(--card)', borderRadius: '4px', overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: '33.3%', background: 'var(--am)', borderRadius: '4px' }} />
                  </div>
                </div>

                <div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '4px' }}>
                    <span>Run 3: Reinforced Pattern in Hindsight</span>
                    <strong className="mono" style={{ color: 'var(--te)' }}>4.5 min (Direct Fix)</strong>
                  </div>
                  <div style={{ height: '8px', background: 'var(--card)', borderRadius: '4px', overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: '25%', background: 'var(--te)', borderRadius: '4px' }} />
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div style={{ marginTop: '16px' }}>
            <div className="lbl">LEARNING TRANSFER ACROSS SERVICES</div>
            <p style={{ fontSize: '13px', color: 'var(--mu)', margin: '0 0 12px' }}>
              Incidents transfer learnings across different microservices sharing root cause signatures:
            </p>
            <div className="step">
              <span className="mono" style={{ flex: 1 }}>Cache Stampede: payments-api &rarr; catalog-service</span>
              <i className="ok">100% transfer</i>
            </div>
            <div className="step">
              <span className="mono" style={{ flex: 1 }}>DB Pool Exhaustion: checkout-api &rarr; orders-api</span>
              <i className="ok">Auto-rollback averted</i>
            </div>
            <div className="step">
              <span className="mono" style={{ flex: 1 }}>Worker Memory Leak: notifications-worker</span>
              <i className="ok">Learned</i>
            </div>
          </div>
        </div>

        <div className="card">
          <div className="lbl">HOW HINDSIGHT POWERS SENTINELMIND</div>
          <div className="stack" style={{ gap: '10px', fontSize: '13px', color: 'var(--mu)', marginTop: '8px' }}>
            <p style={{ margin: 0 }}>
              <strong style={{ color: 'var(--tx)' }}>Retain:</strong> Historian stores structured facts (symptoms, root cause, actions that worked, failed, or worsened) with zero manual formatting.
            </p>
            <p style={{ margin: 0 }}>
              <strong style={{ color: 'var(--tx)' }}>Recall:</strong> Multi-strategy retrieval matches symptoms during Triage, log signatures during Investigation, and action effectiveness during Planning.
            </p>
            <p style={{ margin: 0 }}>
              <strong style={{ color: 'var(--tx)' }}>Reflect:</strong> Cross-incident synthesis generates high-level playbooks and rules, identifying single points of failure.
            </p>
          </div>
        </div>
      </div>

      <div className="stack">
        <div className="card">
          <div className="lbl" style={{ color: 'var(--te)' }}>
            HINDSIGHT REFLECTED PLAYBOOKS ({playbooks.length})
          </div>
          <div style={{ marginTop: '12px' }}>
            {playbooks.length === 0 ? (
              <div className="empty">
                Playbooks are synthesized dynamically as incidents resolve. Seed the demo or run incidents to populate.
              </div>
            ) : (
              playbooks.map((pb, idx) => (
                <div
                  key={idx}
                  style={{
                    background: 'var(--card)',
                    border: '1px solid var(--line)',
                    borderRadius: '10px',
                    padding: '14px',
                    marginBottom: '12px',
                  }}
                >
                  <div className="row">
                    <h4 className="mono" style={{ margin: 0, fontSize: '15px' }}>
                      {pb.root_cause}
                    </h4>
                    <small className="mono" style={{ color: 'var(--mu)' }}>
                      Updated {new Date(pb.updated_at).toLocaleTimeString()}
                    </small>
                  </div>

                  <div style={{ display: 'flex', gap: '8px', margin: '8px 0', flexWrap: 'wrap' }}>
                    {pb.recommended_action && (
                      <span className="chip ok" style={{ margin: 0 }}>
                        &check; First pick: {pb.recommended_action}
                      </span>
                    )}
                    {pb.avoid_action && (
                      <span className="chip no" style={{ margin: 0 }}>
                        &times; Avoid: {pb.avoid_action}
                      </span>
                    )}
                  </div>

                  <p style={{ fontSize: '13px', color: 'var(--tx)', margin: '6px 0 0', lineHeight: 1.5 }}>
                    {pb.synthesis}
                  </p>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
